/* The following code was generated by JFlex 1.4.3 on 4/28/26, 2:45 PM */

/*
 * Copyright 2017 Austin Lehman
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aussom;

import java.math.BigDecimal;
import java.math.BigInteger;

import java_cup.runtime.Symbol;
import com.aussom.stdlib.console;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/28/26, 2:45 PM from the specification file
 * <tt>/home/austin/git/gitlab/aussom-base/src/main/jflex/Scanner.jflex</tt>
 */
class Lexer extends sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int C_COMMENT = 4;
  public static final int STRING = 6;
  public static final int YYINITIAL = 0;
  public static final int AUSSOM_DOC = 2;
  public static final int STRING_LIT = 10;
  public static final int STRING_FRMT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\71\1\10\1\0\1\1\1\7\22\0\1\1\1\57\1\66"+
    "\1\64\1\0\1\54\1\62\1\67\1\44\1\45\1\53\1\52\1\43"+
    "\1\3\1\5\1\12\12\4\1\41\1\11\1\60\1\42\1\61\1\56"+
    "\1\65\4\72\1\2\1\72\24\6\1\50\1\70\1\51\1\0\1\6"+
    "\1\0\1\15\1\26\1\13\1\24\1\17\1\37\1\6\1\35\1\23"+
    "\1\6\1\40\1\14\1\22\1\20\1\30\1\25\1\6\1\27\1\16"+
    "\1\31\1\21\1\32\1\36\1\33\1\34\1\6\1\46\1\63\1\47"+
    "\1\55\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\3\0\1\4\1\3\1\1\1\5"+
    "\1\6\1\7\1\4\1\10\1\11\14\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\4\1\26\1\27\1\30\1\31\2\4"+
    "\1\32\1\33\1\34\1\35\1\2\1\36\1\2\2\3"+
    "\1\2\1\37\1\40\1\4\2\2\1\41\2\2\1\42"+
    "\1\2\1\43\1\4\1\2\1\44\1\45\1\1\2\0"+
    "\1\3\1\46\1\47\12\1\1\50\12\1\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\0\1\2\1\67\1\3"+
    "\1\70\1\0\1\71\1\72\2\0\1\73\1\0\2\6"+
    "\1\74\1\0\10\1\1\75\12\1\1\76\3\1\1\77"+
    "\1\100\1\0\1\101\1\0\1\6\1\0\1\102\1\1"+
    "\1\103\3\1\1\104\1\105\1\1\1\106\10\1\1\107"+
    "\3\1\2\0\1\110\1\111\11\1\1\112\1\1\1\113"+
    "\1\114\1\115\2\0\1\116\1\117\1\120\3\1\1\121"+
    "\2\1\1\122\1\123\1\124\1\125\1\1\1\126\1\127"+
    "\4\1\1\130\1\131";

  private static int [] zzUnpackAction() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u0162\0\u02c4\0\u02ff"+
    "\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0162\0\u0162\0\u0162"+
    "\0\u0162\0\u0162\0\u0162\0\u0162\0\u0639\0\u0674\0\u06af\0\u06ea"+
    "\0\u0162\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811\0\u0162\0\u084c"+
    "\0\u0887\0\u0162\0\u08c2\0\u0162\0\u08fd\0\u0938\0\u0973\0\u09ae"+
    "\0\u09e9\0\u0162\0\u0a24\0\u0a5f\0\u0162\0\u0162\0\u0a9a\0\u0ad5"+
    "\0\u0162\0\u0b10\0\u0162\0\u0b4b\0\u0b86\0\u0162\0\u0162\0\u0bc1"+
    "\0\u0bfc\0\u0c37\0\u0c72\0\u0162\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e"+
    "\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u019d"+
    "\0\u0f36\0\u0f71\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3"+
    "\0\u110e\0\u1149\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162"+
    "\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162\0\u0162"+
    "\0\u1184\0\u11bf\0\u0162\0\u11fa\0\u0162\0\u1235\0\u0162\0\u0162"+
    "\0\u1270\0\u12ab\0\u0162\0\u12e6\0\u1321\0\u135c\0\u0162\0\u1397"+
    "\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f"+
    "\0\u019d\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c"+
    "\0\u1747\0\u1782\0\u17bd\0\u019d\0\u17f8\0\u1833\0\u186e\0\u019d"+
    "\0\u0162\0\u18a9\0\u0162\0\u18e4\0\u12e6\0\u191f\0\u0162\0\u195a"+
    "\0\u019d\0\u1995\0\u19d0\0\u1a0b\0\u019d\0\u019d\0\u1a46\0\u019d"+
    "\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e"+
    "\0\u019d\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u019d\0\u019d"+
    "\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2\0\u1f1d"+
    "\0\u1f58\0\u019d\0\u1f93\0\u019d\0\u019d\0\u019d\0\u1fce\0\u2009"+
    "\0\u019d\0\u019d\0\u019d\0\u2044\0\u207f\0\u20ba\0\u019d\0\u20f5"+
    "\0\u2130\0\u019d\0\u0162\0\u0162\0\u019d\0\u216b\0\u019d\0\u019d"+
    "\0\u21a6\0\u21e1\0\u221c\0\u2257\0\u019d\0\u019d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\11\1\15"+
    "\1\10\1\16\1\17\1\20\2\11\1\21\1\22\1\23"+
    "\2\11\1\24\1\25\1\26\1\27\1\30\1\11\1\31"+
    "\4\11\1\32\1\33\1\11\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\7\1\10\1\11\10\63\1\64"+
    "\42\63\1\65\17\63\10\66\1\10\42\66\1\67\17\66"+
    "\7\70\2\71\55\70\1\72\1\70\1\73\1\74\1\70"+
    "\7\75\1\76\1\64\55\75\1\77\1\75\1\100\1\101"+
    "\1\75\7\102\2\71\56\102\1\103\1\104\1\105\1\102"+
    "\75\0\1\11\1\0\1\11\1\0\1\11\4\0\26\11"+
    "\31\0\1\11\3\0\1\106\36\0\1\107\32\0\1\110"+
    "\1\0\1\13\1\111\1\11\4\0\4\11\1\110\21\11"+
    "\31\0\1\11\5\0\1\112\75\0\1\10\74\0\1\113"+
    "\27\0\1\114\10\0\1\115\21\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\1\11\1\116\1\117\23\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\16\11\1\120\4\11\1\121\2\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\1\11\1\122"+
    "\3\11\1\123\12\11\1\124\5\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\4\11\1\125"+
    "\1\11\1\126\17\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\5\11\1\127\16\11\1\130"+
    "\1\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\4\11\1\131\21\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\6\11\1\132"+
    "\5\11\1\133\11\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\14\11\1\134\11\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\4\11\1\135\21\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\14\11\1\136\5\11\1\137"+
    "\3\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\22\11\1\140\3\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\2\11\1\141"+
    "\12\11\1\142\10\11\31\0\1\11\41\0\1\143\1\144"+
    "\72\0\1\145\72\0\1\146\7\0\1\147\62\0\1\150"+
    "\72\0\1\151\42\0\1\152\122\0\1\153\72\0\1\154"+
    "\72\0\1\155\112\0\1\156\73\0\1\157\51\0\1\160"+
    "\116\0\1\161\4\0\10\63\1\0\42\63\1\0\17\63"+
    "\10\162\1\0\1\162\1\163\40\162\1\65\17\162\10\66"+
    "\1\0\42\66\1\0\17\66\10\164\1\0\1\164\1\165"+
    "\40\164\1\67\17\164\7\70\2\0\55\70\1\0\1\70"+
    "\1\0\2\70\7\0\2\71\60\0\1\71\21\0\1\64"+
    "\1\166\5\0\1\76\1\0\1\101\34\0\1\167\1\0"+
    "\1\170\2\0\7\70\2\71\55\70\1\0\1\70\1\0"+
    "\1\74\1\70\66\0\1\171\25\0\1\166\44\0\1\172"+
    "\1\0\1\170\2\0\7\102\2\0\56\102\2\0\2\102"+
    "\20\0\1\64\1\166\5\0\1\76\1\0\1\101\35\0"+
    "\1\173\1\170\2\0\7\102\2\71\56\102\2\0\1\105"+
    "\1\102\2\0\1\11\1\174\1\175\1\0\1\11\4\0"+
    "\26\11\11\0\1\174\17\0\1\11\4\0\1\176\73\0"+
    "\1\177\65\0\7\113\2\0\62\113\53\0\1\200\21\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\2\11\1\201"+
    "\23\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\3\11\1\202\12\11\1\203\7\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\2\11\1\204\23\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\10\11\1\205\15\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\3\11\1\206\22\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\6\11\1\207\17\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\16\11\1\210\7\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\23\11\1\211\2\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\1\11\1\212\24\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\1\213\2\11\1\214\22\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\24\11\1\215\1\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\13\11\1\216\12\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\10\11\1\217\4\11\1\220\10\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\4\11"+
    "\1\221\21\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\16\11\1\222\7\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\6\11"+
    "\1\223\12\11\1\224\4\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\14\11\1\225\11\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\10\11\1\226\15\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\1\11\1\227\24\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\14\11\1\230\11\11\31\0\1\11\66\0\1\231"+
    "\4\0\10\162\1\0\1\162\1\0\40\162\1\0\17\162"+
    "\10\164\1\0\1\164\1\0\40\164\1\0\17\164\2\0"+
    "\1\232\1\0\1\232\6\0\1\232\1\0\1\232\1\0"+
    "\1\232\4\0\1\232\1\0\1\232\10\0\1\232\32\0"+
    "\1\232\66\0\1\233\74\0\1\234\6\0\1\235\70\0"+
    "\1\11\1\0\1\175\1\0\1\11\4\0\26\11\31\0"+
    "\1\11\2\0\1\236\1\0\1\176\12\0\1\236\53\0"+
    "\12\237\1\0\40\237\1\0\17\237\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\3\11\1\240\22\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\4\11\1\241\21\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\1\242\25\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\16\11"+
    "\1\243\7\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\16\11\1\244\7\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\4\11"+
    "\1\245\21\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\7\11\1\246\16\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\4\11"+
    "\1\247\21\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\1\11\1\250\24\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\1\11"+
    "\1\251\24\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\16\11\1\252\7\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\2\11"+
    "\1\253\23\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\1\11\1\254\24\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\17\11"+
    "\1\255\6\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\16\11\1\256\7\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\2\11"+
    "\1\257\23\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\6\11\1\260\17\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\4\11"+
    "\1\261\21\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\15\11\1\262\10\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\1\11"+
    "\1\263\24\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\3\11\1\264\22\11\31\0\1\11"+
    "\2\0\1\265\1\0\1\265\6\0\1\265\1\0\1\265"+
    "\1\0\1\265\4\0\1\265\1\0\1\265\10\0\1\265"+
    "\32\0\1\265\66\0\1\266\7\0\1\174\1\235\45\0"+
    "\1\174\22\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\3\11\1\267\22\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\22\11\1\270\3\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\10\11\1\271\15\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\1\272\25\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\14\11"+
    "\1\273\11\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\6\11\1\274\17\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\2\11"+
    "\1\275\23\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\6\11\1\276\17\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\10\11"+
    "\1\277\15\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\2\11\1\300\23\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\4\11"+
    "\1\301\21\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\25\11\1\302\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\14\11\1\303"+
    "\11\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\23\11\1\304\2\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\4\11\1\305"+
    "\21\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\4\11\1\306\21\11\31\0\1\11\2\0"+
    "\1\307\1\0\1\307\6\0\1\307\1\0\1\307\1\0"+
    "\1\307\4\0\1\307\1\0\1\307\10\0\1\307\32\0"+
    "\1\307\70\0\1\310\4\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\1\311\25\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\22\11\1\312\3\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\5\11\1\313\20\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\11\11\1\314\14\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\5\11\1\315\20\11\31\0\1\11\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\1\11\1\316\24\11"+
    "\31\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\1\317\25\11\31\0\1\11\2\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\16\11\1\320\7\11\31\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\1\321\25\11\31\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\5\11\1\322\20\11\31\0\1\11"+
    "\2\0\1\323\1\0\1\323\6\0\1\323\1\0\1\323"+
    "\1\0\1\323\4\0\1\323\1\0\1\323\10\0\1\323"+
    "\32\0\1\323\66\0\1\324\6\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\4\11\1\325\21\11\31\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\1\11\4\0\1\326"+
    "\25\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\16\11\1\327\7\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\4\11\1\330"+
    "\21\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\16\11\1\331\7\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\4\11\1\332"+
    "\21\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\4\11\1\333\21\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\15\11\1\334"+
    "\10\11\31\0\1\11\2\0\1\11\1\0\1\11\1\0"+
    "\1\11\4\0\11\11\1\335\14\11\31\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\0\1\11\4\0\24\11\1\336"+
    "\1\11\31\0\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8850];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\1\3\0\2\11\5\1\1\11\17\1\7\11\4\1"+
    "\1\11\5\1\1\11\2\1\1\11\1\1\1\11\5\1"+
    "\1\11\2\1\2\11\2\1\1\11\1\1\1\11\2\1"+
    "\2\11\1\1\2\0\1\1\1\11\26\1\16\11\1\0"+
    "\1\1\1\11\1\1\1\11\1\0\2\11\2\0\1\11"+
    "\1\0\2\1\1\11\1\0\30\1\1\11\1\0\1\11"+
    "\1\0\1\1\1\0\1\11\25\1\2\0\20\1\2\0"+
    "\12\1\2\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  String fileName = "<unknown>";
  boolean hasErrors = false;

  private Symbol symbol(int sym) {
    return new Symbol(sym, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int sym, Object val) {
    return new Symbol(sym, yyline+1, yycolumn+1, val);
  }

  private void error(String message) {
    this.hasErrors = true;
    console.get().err(this.fileName + " [" + (yyline+1) + "]: Error at line "
      + (yyline+1) + ", column " + (yycolumn+1) + " : " + message);
  }

  public boolean hasErrors() {
    return this.hasErrors;
  }

  Lexer(java.io.Reader in, String FileName) {
    this(in);
    this.fileName = FileName;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 50: 
          { return symbol(sym.LTEQ);
          }
        case 90: break;
        case 79: 
          { return symbol(sym.SWITCH);
          }
        case 91: break;
        case 21: 
          { return symbol(sym.MODULUS);
          }
        case 92: break;
        case 58: 
          { string.append("\\");
          }
        case 93: break;
        case 9: 
          { return symbol(sym.DI);
          }
        case 94: break;
        case 53: 
          { return symbol(sym.OR);
          }
        case 95: break;
        case 13: 
          { return symbol(sym.LPAREN);
          }
        case 96: break;
        case 62: 
          { return symbol(sym.TRY);
          }
        case 97: break;
        case 80: 
          { return symbol(sym.EXTERN);
          }
        case 98: break;
        case 42: 
          { return symbol(sym.SET);
          }
        case 99: break;
        case 32: 
          { yybegin(YYINITIAL);
								return symbol(sym.STRING,
								string.toString());
          }
        case 100: break;
        case 47: 
          { return symbol(sym.MODULUSEQ);
          }
        case 101: break;
        case 44: 
          { return symbol(sym.PLEQ);
          }
        case 102: break;
        case 68: 
          { return symbol(sym.ELSE);
          }
        case 103: break;
        case 30: 
          { string.append('\n');
          }
        case 104: break;
        case 35: 
          { yybegin(YYINITIAL);
								return symbol(sym.STRING, string.toString());
          }
        case 105: break;
        case 57: 
          { string.append('\"');
          }
        case 106: break;
        case 7: 
          { return symbol(sym.DOT);
          }
        case 107: break;
        case 51: 
          { return symbol(sym.GTEQ);
          }
        case 108: break;
        case 10: 
          { return symbol(sym.COLON);
          }
        case 109: break;
        case 37: 
          { return symbol(sym.MIEQ);
          }
        case 110: break;
        case 52: 
          { return symbol(sym.AND);
          }
        case 111: break;
        case 88: 
          { return symbol(sym.PROTECTED);
          }
        case 112: break;
        case 33: 
          { string.append('\r');
          }
        case 113: break;
        case 28: 
          { string.setLength(0); yybegin(STRING);
          }
        case 114: break;
        case 19: 
          { return symbol(sym.PL);
          }
        case 115: break;
        case 55: 
          { yybegin(YYINITIAL);
	                            return symbol(sym.AUSSOM_DOC, string.toString());
          }
        case 116: break;
        case 66: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 3;
          { string.setLength(0); yybegin(AUSSOM_DOC);
          }
        case 117: break;
        case 40: 
          { return symbol(sym.IF);
          }
        case 118: break;
        case 5: 
          { return symbol(sym.MI);
          }
        case 119: break;
        case 59: 
          { string.append('\'');
          }
        case 120: break;
        case 23: 
          { return symbol(sym.NOT);
          }
        case 121: break;
        case 26: 
          { return symbol(sym.COUNT);
          }
        case 122: break;
        case 34: 
          { string.append('\t');
          }
        case 123: break;
        case 49: 
          { return symbol(sym.NOTEQ);
          }
        case 124: break;
        case 76: 
          { return symbol(sym.WHILE);
          }
        case 125: break;
        case 8: 
          { return symbol(sym.SEMI);
          }
        case 126: break;
        case 73: 
          { return symbol(sym.CATCH);
          }
        case 127: break;
        case 12: 
          { return symbol(sym.COMMA);
          }
        case 128: break;
        case 60: 
          { return symbol(sym.ETCETERA);
          }
        case 129: break;
        case 29: 
          { string.setLength(0); yybegin(STRING_LIT);
          }
        case 130: break;
        case 84: 
          { string.append("\"\"\"");
          }
        case 131: break;
        case 54: 
          { return symbol(sym.INSERT);
          }
        case 132: break;
        case 89: 
          { return symbol(sym.INSTANCEOF);
          }
        case 133: break;
        case 77: 
          { return symbol(sym.BOOL, false);
          }
        case 134: break;
        case 43: 
          { return symbol(sym.EQEQ);
          }
        case 135: break;
        case 70: 
          { return symbol(sym.NULL);
          }
        case 136: break;
        case 65: 
          { yybegin(YYINITIAL); 
								return symbol(sym.STRING, string.toString());
          }
        case 137: break;
        case 18: 
          { return symbol(sym.RBRACE);
          }
        case 138: break;
        case 69: 
          { return symbol(sym.ENUM);
          }
        case 139: break;
        case 64: 
          { string.setLength(0); yybegin(STRING_FRMT);
          }
        case 140: break;
        case 45: 
          { return symbol(sym.PLPL);
          }
        case 141: break;
        case 87: 
          { return symbol(sym.PRIVATE);
          }
        case 142: break;
        case 82: 
          { return symbol(sym.RETURN);
          }
        case 143: break;
        case 27: 
          { return symbol(sym.AT);
          }
        case 144: break;
        case 15: 
          { return symbol(sym.LBRACKET);
          }
        case 145: break;
        case 41: 
          { return symbol(sym.CALLBACK);
          }
        case 146: break;
        case 31: 
          { /* Do nothing. */
          }
        case 147: break;
        case 75: 
          { return symbol(sym.THROW);
          }
        case 148: break;
        case 56: 
          { yybegin(YYINITIAL);
          }
        case 149: break;
        case 36: 
          { return symbol(sym.MIMI);
          }
        case 150: break;
        case 17: 
          { return symbol(sym.LBRACE);
          }
        case 151: break;
        case 72: 
          { return symbol(sym.CLASSDEF);
          }
        case 152: break;
        case 78: 
          { return symbol(sym.STATIC);
          }
        case 153: break;
        case 6: 
          { String ntxt = yytext();
								if(ntxt.contains(".") || ntxt.contains("e") || ntxt.contains("E"))
								{
									BigDecimal val = null;
									try{ val = new BigDecimal(ntxt); }
									catch(NumberFormatException e)
									{
										error("Number format exception <" + ntxt + ">");
									}
									return symbol(sym.DOUBLE, val);
								}
								else
								{
									BigInteger val = null;
									try{ val = new BigInteger(ntxt); }
									catch(NumberFormatException e)
									{
										error("Number format exception <" + ntxt + ">");
									}
									return symbol(sym.INT, val);
								}
          }
        case 154: break;
        case 86: 
          { return symbol(sym.DEFAULT);
          }
        case 155: break;
        case 16: 
          { return symbol(sym.RBRACKET);
          }
        case 156: break;
        case 71: 
          { return symbol(sym.BOOL, true);
          }
        case 157: break;
        case 25: 
          { return symbol(sym.GT);
          }
        case 158: break;
        case 85: 
          { return symbol(sym.INCLUDE);
          }
        case 159: break;
        case 81: 
          { return symbol(sym.PUBLIC);
          }
        case 160: break;
        case 38: 
          { return symbol(sym.DIEQ);
          }
        case 161: break;
        case 3: 
          { /* ignore */
          }
        case 162: break;
        case 11: 
          { return symbol(sym.EQ);
          }
        case 163: break;
        case 14: 
          { return symbol(sym.RPAREN);
          }
        case 164: break;
        case 4: 
          { /* throw new Error("Illegal character <" + String.ValueOf((int)yytext()) + ">");*/
							error("Illegal character <" + String.valueOf((int)yytext().charAt(0)) + ">");
          }
        case 165: break;
        case 2: 
          { string.append( yytext() );
          }
        case 166: break;
        case 74: 
          { return symbol(sym.BREAK);
          }
        case 167: break;
        case 63: 
          { return symbol(sym.FOR);
          }
        case 168: break;
        case 39: 
          { yybegin(C_COMMENT);
          }
        case 169: break;
        case 22: 
          { return symbol(sym.MISSNULL);
          }
        case 170: break;
        case 67: 
          { return symbol(sym.CASE);
          }
        case 171: break;
        case 48: 
          { return symbol(sym.FLOORDIV);
          }
        case 172: break;
        case 20: 
          { return symbol(sym.MU);
          }
        case 173: break;
        case 24: 
          { return symbol(sym.LT);
          }
        case 174: break;
        case 83: 
          { string.append((char)Integer.parseInt(yytext().substring(2), 16));
          }
        case 175: break;
        case 1: 
          { return symbol(sym.IDENT, yytext());
          }
        case 176: break;
        case 61: 
          { return symbol(sym.NEW);
          }
        case 177: break;
        case 46: 
          { return symbol(sym.MUEQ);
          }
        case 178: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return symbol( sym.EOF );
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
